#!/usr/bin/env bash
# Install ngix, setup it on port 80 HTTP and write HOlberton SChool in index
# file

apt-get -y update
apt-get -y install nginx
uff allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
