#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School!' > /var/www/html/index.html
sudo mv index.html /var/www/html/
sudo service nginx restart
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html/
sudo sed -i "/listen 80 default_server;/a\\\trewrite ^/redirect_me https://github.com/AndresSern permanent;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restar
