#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another
# page.

path="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Holberton School!' > index.html
sudo mv index.html /var/www/html/

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html/

sudo sed -i "/listen 80 default_server;/a\\\trewrite ^/redirect_me https://github.com/AndresSern permanent;" $path
sudo sed -i "/server_name _;/a\\\terror_page 404 /404.html;" $path
sudo sed -i "/server_name _;/a\\\tadd_header X-Served-By \"\$HOSTNAME\";" $path

sudo service nginx restart
