#!/usr/bin/env bash
# Script that generates a MySql dump and creates a compressd archive out of it
DATE=$(date + '%d-%m-%Y')
mysqldump -uroot --password="$1" --all-databases > backup.sql
sudo tar -czf "$DATE".tar.gz backup.sql
