#!/usr/bin/env bash
# Script that generates a MySql dump and creates a compressd archive out of it
DATE=$(date + '%d-%m-%Y')
mysqldump -u root -p"$1" --all-databases > backup.sql
sudo tar -cvzf "$DATE".tar.gz backup.sql
