#!/usr/bin/env bash
#This prints Holberton School 10 times with while
count=1
while [ "$count" -le 10 ]; 
do
	if [ "$count" -eq 9 ]
	then
		echo "Hi"	
	else
		echo "Holberton School"
		
	fi
	((count++))
done
