#!/usr/bin/env bash
# BASH script that configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sudo echo "127.0.0.2" >  /etc/hosts
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts
