#!/usr/bin/env bash
# BASH script that configures an Ubuntu server with the below requirements
#  localhost resolves to 127.0.0.2
#  facebook.com resolves to 8.8.8.8

sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i '2s/^/8.8.8.8	facebook.com\n/' /etc/hosts

